-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 20:20:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`alunos front-end`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos front-end` (
  `Id frontend` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `cpf` INT NULL,
  `nasc` DATE NULL,
  PRIMARY KEY (`Id frontend`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos back-end`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos back-end` (
  `idBACK END` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `cpf` INT NULL,
  `nasc` DATE NULL,
  PRIMARY KEY (`idBACK END`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos full stack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos full stack` (
  `idfull stack` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sobrenome` VARCHAR(100) NULL,
  `cpf` INT NULL,
  `nasc` DATE NULL,
  PRIMARY KEY (`idfull stack`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `idcursos` INT NOT NULL,
  `front_end` VARCHAR(100) NULL,
  `back_end` VARCHAR(100) NULL,
  `full_stack` VARCHAR(100) NULL,
  `FRONT END_Id frontend` INT NOT NULL,
  `FULL STACK_idfull stack` INT NOT NULL,
  `BACK END_idBACK END` INT NOT NULL,
  PRIMARY KEY (`idcursos`),
  INDEX `fk_cursos_FRONT END_idx` (`FRONT END_Id frontend` ASC) VISIBLE,
  INDEX `fk_cursos_FULL STACK1_idx` (`FULL STACK_idfull stack` ASC) VISIBLE,
  INDEX `fk_cursos_BACK END1_idx` (`BACK END_idBACK END` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_FRONT END`
    FOREIGN KEY (`FRONT END_Id frontend`)
    REFERENCES `mydb`.`alunos front-end` (`Id frontend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_FULL STACK1`
    FOREIGN KEY (`FULL STACK_idfull stack`)
    REFERENCES `mydb`.`alunos full stack` (`idfull stack`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_BACK END1`
    FOREIGN KEY (`BACK END_idBACK END`)
    REFERENCES `mydb`.`alunos back-end` (`idBACK END`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `idturmas` INT NOT NULL,
  `turmas_201` INT NULL,
  `turmas_202` INT NULL,
  `turmas_203` INT NULL,
  PRIMARY KEY (`idturmas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turnos` (
  `idturnos` INT NOT NULL,
  `manhã` VARCHAR(20) NULL,
  `tarde` VARCHAR(20) NULL,
  `noite` VARCHAR(20) NULL,
  PRIMARY KEY (`idturnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos_has_turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos_has_turnos` (
  `cursos_idcursos` INT NOT NULL,
  `turnos_idturnos` INT NOT NULL,
  PRIMARY KEY (`cursos_idcursos`, `turnos_idturnos`),
  INDEX `fk_cursos_has_turnos_turnos1_idx` (`turnos_idturnos` ASC) VISIBLE,
  INDEX `fk_cursos_has_turnos_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  CONSTRAINT `fk_cursos_has_turnos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_has_turnos_turnos1`
    FOREIGN KEY (`turnos_idturnos`)
    REFERENCES `mydb`.`turnos` (`idturnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas_has_cursos` (
  `turmas_idturmas` INT NOT NULL,
  `cursos_idcursos` INT NOT NULL,
  PRIMARY KEY (`turmas_idturmas`, `cursos_idcursos`),
  INDEX `fk_turmas_has_cursos_cursos1_idx` (`cursos_idcursos` ASC) VISIBLE,
  INDEX `fk_turmas_has_cursos_turmas1_idx` (`turmas_idturmas` ASC) VISIBLE,
  CONSTRAINT `fk_turmas_has_cursos_turmas1`
    FOREIGN KEY (`turmas_idturmas`)
    REFERENCES `mydb`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turmas_has_cursos_cursos1`
    FOREIGN KEY (`cursos_idcursos`)
    REFERENCES `mydb`.`cursos` (`idcursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
